### ISSUE TITLE
Get list of iNat IDs

### ISSUE THREAD

**Issue by simonrolph** [AugustT/BioHack_iNat#1]

**Comment by PietrH** [comment]
The export is in 1efda59c8532c96654d752ccefe99a192b629789, the code in dd99a2b2b66819550e18351886b05fd396cd7c8f, the export itself in a9f76d200cb99a901122eab4f192e79750bbaa75

But can also be found as GBIF.org (09 November 2021) GBIF Occurrence Download https://doi.org/10.15468/dl.svwnrp 

I only saw the issue now, otherwise i'd have used a pull request instead

**Comment by PietrH** [comment]
@simonrolph Do you need help converting the usernames from recordedBy to inat user id's?

**Comment by simonrolph** [comment]
Seems like the list of users are inconsitent in format, what is recordedBy derived from?

```
pakitomv
javixu
Christoph Moning
Miguel A. Casado
mammal
kiksalinas-anapri
Pablo de la Fuente Brun
whodden
tullman
José Luis Romero Rego
```

**Comment by simonrolph** [comment]
First chunk of this code seems to work for matching either usernames or names to username: https://github.com/AugustT/BioHack_iNat/blob/main/generating_inat_baseline.Rmd
